[workspace]
authors = ["Rohit Goswami <rog32@hi.is>"]
channels = ["conda-forge", "bioconda"]
name = "gprd_zbl"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
dvc = ">=3.62.0,<4"
dvc-webdav = ">=3.0.0,<4"
zlib = ">=1.3.1,<2"

[pypi-dependencies]
rgpycrumbs = { path = "./subrepos/rgpycrumbs", editable=true }

[pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cpu"]

[activation]
# Needed to set the fake scm_version for editable pypi deps since subrepos are
# not really git repositories
scripts = ["scripts/env_setup.sh"]

[feature.docs.dependencies]
hugo = "*"
pnpm = "*"

[feature.eon.dependencies]
# Kanged mostly from the pixi.toml within
# This is a customized amalgamation of deps
eigen = ">=3.4,<3.5"
# Pin python for torch
python = ">=3.11.5,<3.13"
# End manual pins
cmake = ">=4.0.3,<5"
highfive = ">=2.10.1,<3"
meson = ">=1.8.2,<2"
ninja = ">=1.12.1,<2"
pkgconf = ">=2.4.3,<3"
openblas = ">=0.3.29,<0.4"
pip = ">=25.1.1,<26"
pipx = ">=1.7.1,<2"
numpy = ">=2.3.0,<3"
compilers = ">=1.9.0,<2"
gfortran = ">=13.3.0,<13.4"
fmt = ">=11.1.4,<12"
spdlog = ">=1.15.3,<2"
h5py = ">=3.14.0,<4"
gtest = ">=1.17.0,<2"
pycapnp = ">=2.0.0,<3"
capnproto = ">=1.0.2,<2"
aria2 = ">=1.37.0,<2"
xtb = ">=6.7.1,<7"
xtb-python = ">=22.1,<23"
tblite-python = ">=0.4.0,<0.5"
ceres-solver = ">=2.2.0,<3"
polars = ">=1.33.1,<2"

[feature.optdev]
platforms = ["linux-64"]

[feature.optdev.dependencies]
mold = ">=2.40.2,<3"
ccache = ">=4.11.3,<5"

[feature.asenwchem.dependencies]
pybind11 = ">=3.0.0,<4"

[feature.asenwchem.pypi-dependencies]
# Technically only for the ASE wrapper
psutil = ">=7.0.0, <8"

[feature.metatomic]
# Not sure I'll use this yet...
# can't hurt though!
# vesin torch has a wheel issue with macos x86_64
platforms = ["linux-64", "osx-arm64"]

[feature.metatomic.pypi-dependencies]
torch = ">=2.7.1, <3"
metatomic-torch = ">=0.1.2, <0.2"
metatensor-torch = ">=0.7.6, <0.8"
metatensor = ">=0.2.0, <0.3"
vesin-torch = ">=0.3.7, <0.4"
vesin = ">=0.3.7, <0.4"
metatrain = ">=2025.8.1, <2026"

[feature.analysis.dependencies]
ase = ">=3.26.0,<4"
h5py = ">=3.14.0,<4"
ipython = ">=9.5.0,<10"
mlflow = ">=3.2.0,<4"
seaborn = ">=0.13.2,<0.14"
polars = ">=1.33.1,<2"
r = ">=4.5,<4.6"
radian = ">=0.6.15,<0.7"
r-httpgd = ">=2.0.4,<3"
r-scales = ">=1.4.0,<2"
r-patchwork = ">=1.3.2,<2"
r-tidyverse = ">=2.0.0,<3"
r-ggnewscale = ">=0.5.2,<0.6"
r-latex2exp = ">=0.9.6,<0.10"
r-broom = ">=1.0.10,<2"
r-devtools = ">=2.4.5,<3"
r-ggthemes = ">=5.1.0,<6"
r-ggridges = ">=0.5.7,<0.6"
r-ggrepel = ">=0.9.6,<0.10"
r-hmisc = ">=5.2_3,<6"
r-waffle = ">=1.0.2,<2"
r-ggdist = ">=3.3.3,<4"
r-showtext = ">=0.9_7,<0.10"
r-sysfonts = ">=0.8.9,<0.9"
tblite-python = ">=0.4.0,<0.5"
r-ggimage = ">=0.3.4,<0.4"

[feature.analysis.pypi-dependencies]
chemparseplot = { path = "./subrepos/chemparseplot", editable=true }
cmcrameri = ">=1.9, <2"
sympy = ">=1.13.3, <2"

[feature.analysis.tasks.mkira]
cwd = "subrepos/IterativeRotationsAssignments/src"
cmd = "make clean && make all"

[feature.snakemake.dependencies]
snakemake = ">=9.11.2,<10"

[feature.snakemake.pypi-dependencies]
snakemake-executor-plugin-slurm = ">=1.7.0,<1.8.0"
snakemake-storage-plugin-fs = ">=1.1.2, <2"
snakemake-executor-plugin-cluster-generic = ">=1.0.9, <2"

[feature.nwchem.dependencies]
openmpi = "*"

[feature.brms.dependencies]
r-devtools = ">=2.4.5,<3"
r-brms = ">=2.23.0,<3"
r-tidybayes = ">=3.0.7,<4"
radian = ">=0.6.15,<0.7"
r-httpgd = ">=2.0.4,<3"
r-ragg = ">=1.5.0,<2"
r-tidyverse = ">=2.0.0,<3"
r-reprex = ">=2.1.1,<3"
cmdstan = ">=2.37.0,<3"
r-cmdstanr = ">=0.9.0,<0.10"
r-archive = ">=1.1.12,<2"
r-ggthemes = ">=5.1.0,<6"
r-hexbin = ">=1.28.5,<2"
r-performance = ">=0.15.1,<0.16"
r-zoo = ">=1.8_14,<2"
r-glmmtmb = ">=1.1.9,<2"
r-showtext = ">=0.9_7,<0.10"
r-sysfonts = ">=0.8.9,<0.9"

[environments]
docs = {features = ["docs"]}
eon = {features = ["eon", "asenwchem", "metatomic", "optdev", "analysis", "snakemake", "nwchem"]}
analysis = {features = ["analysis"]}
brms = {features = ["brms"]}

[tasks.docdeps]
cwd = "docs"
cmd = "pnpm install"

[feature.docs.tasks.devdocs]
cwd = "docs"
cmd = "hugo serve"
depends-on = [
  { task = "docdeps", environment = "docs" },
]


[feature.eon.tasks.setupeon]
cwd = "subrepos/eOn"
# Remember that the mold stuff assumes that the user has a UNIX machine However
# dropping mold does nothing but leads to slightly longer build times so it
# isn't an issue
# For exact reproducibility -Dwith_ase_nwchem should be used but it shouldn't matter
# For debugging set
# --buildtype debug -Db_sanitize=address
# To prevent the subproject from leaking into the EON history, it is easier to
# simply rsync in since it is ignored at that path anyway
#
# -Dwith_metatomic=True -Dpip_metatomic=True \
# -Dtorch_version=2.7 \
cmd = """
rsync -vaz ../gpr_optim subprojects && \
meson setup bbdir --reconfigure \
      --prefix=$CONDA_PREFIX \
      --libdir=lib --buildtype {{ buildtype }} \
      --native-file nativeFiles/mold.ini \
      --native-file nativeFiles/ccache_gnu.ini \
      -Dwith_xtb=False \
      -Dwith_tests=True \
      -Dwith_gprd=True
"""
args = ["buildtype"]

[feature.eon.tasks.mkeon]
cwd = "subrepos/eOn"
args = ["buildtype"]
depends-on = [
  { task = "setupeon", environment = "eon", "args" = ["{{buildtype}}"] },
]
cmd = """
meson compile -C bbdir && \
meson install -C bbdir
"""

[feature.eon.tasks.mknwchem]
# Corresponds to https://github.com/nwchemgit/nwchem/pull/1145
args = [{arg = "commitHash", default = "4c48fa339ec671bd78c1ebeea0c1f64104646267"}]
cmd = """
./scripts/build_nwchem.sh {{ commitHash }}
"""

[feature.eon.tasks.tsteon]
cwd = "subrepos/eOn"
depends-on = [
  { task = "mkeon", environment = "eon" },
]
cmd = """
meson test -C bbdir
"""

[feature.eon.tasks.tsteongp]
cwd = "subrepos/eOn"
depends-on = [
  { task = "mkeon", environment = "eon" },
]
cmd = """
meson test -C bbdir test_gprpot -vvv
"""
