# To use:
#
#   $ micromamba env create -f environment.yml  # `micromamba` works too for this command
#   $ micromamba activate gprd
#
name: gprd
channels:
  - conda-forge
dependencies:
  - compilers
  - meson
  - cmake
  - gfortran
  - pkg-config
  - gtest
  - highfive
  # Pinned
  - eigen==3.4.0
